### ISSUE TITLE
Web site uses roudned corners for images that destroys important details

### ISSUE THREAD

**Issue by Mart-Bogdan** [llenotre/blog#1]
![image](https://github.com/llenotre/maestro/assets/775038/77119c49-6278-4f13-8553-f94fa5c71829)

Instead of text `bash-5.1` I can se only part of it, smth like `\ash-5.1` 

https://blog.lenot.re/a/introduction

**Comment by llenotre** [comment]
Hello

Thank you for the report!
I didn't see it until now because I usually test on very large displays, which tends to reduce the rounding compared to the size of the image.

I am going to fix this

**Comment by llenotre** [comment]
Fixed and deployed in production!
